### ISSUE TITLE
 TypeError: _imgixCoreJs.default is not a constructor when running in Fastboot

### ISSUE THREAD

**Issue by neophene** [imgix/ember-cli-imgix#185]
**Describe the bug**

```
 TypeError: _imgixCoreJs.default is not a constructor
    at Class.<anonymous> (/var/folders/9g/nfcgnfjn1bnc49cwmt1ndgmh0000gn/T/broccoli-41819Wb9zbaIfSI95/out-301-append_ember_auto_import_analyzer/assets/addon-tree-output/ember-cli-imgix/components/imgix-image.js:117:1)
    at /var/folders/9g/nfcgnfjn1bnc49cwmt1ndgmh0000gn/T/broccoli-41819Wb9zbaIfSI95/out-301-append_ember_auto_import_analyzer/assets/@ember/-internals/metal/index.js:1881:1
```

Everything seems to be working fine.. it just outputs that.

**To Reproduce**
New ember project, add fastboot, then add this addon and setup a demo image then ember s.

OR
Simple repo with error.
Clone this repo, yarn install and ember s.
https://github.com/neophene/imgix-fastboot-error-test

This is my first time reporting an issue, so if i left anything out let me know.

**Comment by frederickfogerty** [comment]
Hey @neophene, thanks for opening this issue! Definitely looks like something is not working right here, so I'll raise this with the team and see if we can have a look at this at some time in the near future. Unfortunately I can't think of a workaround for this off the top of my head. 

In the meantime please let me know if you find any solutions or workarounds, or if you have any tips for when we look at this.

**Comment by neophene** [comment]
Not a clue, unfortunately.

**Comment by sherwinski** [comment]
Closing as there hasn't been much activity here -- but please feel free to comment back if this is still an issue.
