### ISSUE TITLE
Prismic Support

### ISSUE THREAD

**Issue by theklr** [imgix/ember-cli-imgix#209]
From the prismic meetup a couple months ago it was mentioned that you're the image provider for them, I was wondering if there is support for using this in tandem with the prismic api?

**Comment by sherwinski** [comment]
Hey @theklr 👋 
We don't have out-of-the-box support for the prismic API in this library, but I am sure it can be done with a little configuring. I'll see if I can try to throw a small example together that demonstrates it. In the meantime, was there a specific use case you were looking for when using the two together?

**Comment by theklr** [comment]
Just trying to cleanup my app, particularly with lazing loading with a low-res placeholder.

**Comment by sherwinski** [comment]
Closing this issue as it's been some while since there's been any activity here. Happy to keep the discussion going if this still proves to be an issue for anyone else.

@theklr did you ever find a solution for what you were looking for?

**Comment by theklr** [comment]
> @theklr did you ever find a solution for what you were looking for?

Unfortunately not. Business changed platforms
