### ISSUE TITLE
Provide optional LQIP Support during fastboot

### ISSUE THREAD

**Issue by Duder-onomy** [imgix/ember-cli-imgix#40]
Right now, during fastboot we do nothing. 
As we cannot know the size of the viewport, we cannot know the size of elements during fastboot. 
It would be nice if we could add some kind of LQIP support during fastboot, so that images show up immediately and are subsequently replaced when ember revives the DOM. 

A related requirement is we need to ensure that imgix.js (and the related requirement on jsBase64) are decoupled from any DOM and window apis so that it can be used in fastboot/node. Right now, we wrap it in a fastboot transform which essentially skips the entire lib during fastboot. https://github.com/imgix/ember-cli-imgix/blob/master/index.js#L19

Personally, I would like the LQIP flag to be on the individual component invocation level. So that we are not generating these for every image, only the ones that really matter... like above the fold images.

**Comment by frederickfogerty** [comment]
This is closed by #58
