### ISSUE TITLE
Running `npm install` should not update package-lock.json / Non deterministic builds / Cannot guarantee CI build reliability

### ISSUE THREAD

**Issue by Duder-onomy** [imgix/ember-cli-imgix#52]
Right now, because we use NPM, we cannot work on the repo without constantly changing dependency versions. 

Steps to reproduce:
* Clone the repo fresh
* run `npm install` to install dependencies
* run `git status` and observe a package-lock.json diff

Expected:
* No git diff
Result:
* The repo has been changed by simply installing dependencies

Resolution:
We should use something like [`npm-shrinkwrap`](https://docs.npmjs.com/files/shrinkwrap.json) and lock down our dependencies in the package.json (no carrot/tilde deps)
Or switch to a diff package manager like yarn. 

Node version 8.11.3
NPM Version 5.6.0

**Comment by Duder-onomy** [comment]
This is still a problem. Just re-cloned latest master and ran `npm install` and got a git diff in the `package-json.lock`. This is a known problem with `npm` and the principal reason people are using `yarn`.

**Comment by sherwinski** [comment]
Closing as this issue is quite old - but we're happy to reopen if there is still a need for this at some point in the future.
