### ISSUE TITLE
onLoad handler not called when new state passed, but src unchanged

### ISSUE THREAD

**Issue by Duder-onomy** [imgix/ember-cli-imgix#59]
When a `img`'s src does not change the `load` event is not called. This is by design as in fact, nothing has loaded. 
We want to see the loaded event after we have passed new state to `imgix-image` and after the browser loads the image (whether from cache or from network).  We are not trying to express a dependency on an images download, only a dependency on when the browser thinks the image is ready.

Here is a branch that fixes ^ https://github.com/Duder-onomy/ember-cli-imgix/tree/hotfix-image-loaded-from-cache-does-not-fire-on-load

Going to hold off on the full PR until the 'srcset' changes have landed and stabilized.

**Comment by sherwinski** [comment]
Closing as this issue is quite old - but we're happy to reopen if there is still a need for this at some point in the future.
