### ISSUE TITLE
Remove "fallback src" in srcset generation

### ISSUE THREAD

**Issue by jayeb** [imgix/ember-cli-imgix#69]
**Describe the bug**
We're currently adding a "sizeless" source URL to the end of our srcset attributes as a "fallback source", which is incorrect. The "fallback source" for an image element using the srcset attribute should be provided in the src attribute, not at the end of the srcset list.

See the lines in question here: https://github.com/imgix/ember-cli-imgix/blob/master/addon/components/imgix-image.js#L311-L313

**To Reproduce**
N/A

**Expected behaviour**
Every item in the srcset list should include a size descriptor, which in our case is always a width value or a resolution multiplier.

**Information:**
- ember-cli-imgix version: >= 2.0.0

**Additional context**
This issue is also present in imgix-rails, and is being fixed here: imgix/imgix-rails#69

**Comment by sherwinski** [comment]
Addressed in #122
